#!/bin/sh

echo "========================================"
echo "Cloudflare Tunnel - Vikunja"
echo "========================================"
echo ""
echo "⚠️  AVIS DE CONFIGURATION"
echo ""
echo "Pour activer Cloudflare Tunnel, vous devez:"
echo ""
echo "1. Créer un tunnel sur https://dash.cloudflare.com/"
echo "   - Allez dans: Networks → Tunnels → Create a tunnel"
echo "   - Sélectionnez 'Cloudflared'"
echo "   - Donnez le nom: 'vikunja-tunnel'"
echo ""
echo "2. Récupérez les credentials et placez-les dans:"
echo "   ~/.cloudflared/vikunja-tunnel.json"
echo ""
echo "3. Configurez la route dans le dashboard Cloudflare:"
echo "   - Domaine: votre-domaine.com"
echo "   - Service: HTTP"
echo "   - URL: http://localhost:80"
echo ""
echo "4. Redémarrez le conteneur:"
echo "   docker compose restart cloudflared"
echo ""
echo "========================================"
echo ""
echo "En attendant, l'application est accessible:"
echo "  - Localement: http://localhost:8000/vikunja/"
echo "  - Admin BDD: http://localhost:8000/admin/"
echo ""
echo "========================================"
echo ""

# Garder le conteneur actif
exec tail -f /dev/null
